apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: appjava
  template:
    metadata:
      labels:
        app: appjava
    spec:
      containers:
        - name: javadeployment
          image: doh1/java-web-app:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 800m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /java-web-app
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /java-web-app
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: LaodBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: appjava