apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  namespace: monitoring
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: doh1/java-web-app:1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tomcatconfig
              mountPath: /usr/local/tomcat/conf/tomcat-users.xml
              subPath: tomcat-users.xml
      volumes:
        - name: tomcatconfig
          configMap:
            name: javawebappconfig
            items:
              - key: tomcat-users.xml
                path: tomcat-users.xml