apiVersion: v1
kind: LimitRange
metadata:
  namespace: test-ns
  name: limitsrange
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512mi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      type: Container