apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
        - name: nginccontainer
          image: doh1/nginx-web-app:1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: LoadBancer
  ports:
    - port: 80
      targetPort: 80
 selector:
   app: nginxtest