apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavencontainer
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - onee
      containers:
        - name: mavencontainer
          image: doh1/maven-web-app:12
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: maven