apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacontainer
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - maven
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: javacontainer
          image: doh1/java-web-app:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java