apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      imagePullSecrets:
        - name: dockercred
      containers:
        - name: javawebapp
          image: doh1/dohjavawebapp:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javawebapp