apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumepv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data