apiVersion: v1
kind: ResourceQuota
metadata:
  name: memo-cpu-resour
  namespace: test-ns
spec:
  hard:
    pods: 1
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: "2Gi"
    count/deployments.apps: 2
