kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: readonly
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","create","delete","update"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets","daemonsets"]
    verbs: ["get","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full_access_role_binding
  namespace: tesst-ns
subjects:
  - kind: User
    name: doh                         # Map with username
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonlyi
  apiGroup: rbac.authorization.k8s.io