apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-ns
  name: mavenwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: mavenwebapp
          image: maven-web-app:12
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1m
              memory: 1Gi
            limits:
              cpu: 2m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test-ns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: maven
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploymenthpa
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenwebapp
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
